In [1]:
import numpy as np
array3D = np.array([[[ 0.5,  1.2,  2.3],
                     [ 3.0,  4.5,  5.3],
                     [ 6.0,  7.7,  8.1]],
  
                    [[ 9.5, 10.0, 11.2],
                     [12.7, 13.1, 14.5],
                     [15.6, 16.1, 17.7]],
 
                    [[18.7, 19.1, 20.6],
                     [21.7, 22.4, 23.5],
                     [24.9, 25.5, 26.7]]])
 
print(array3D)
print("shape :" +str(array3D.shape))

[[[ 0.5  1.2  2.3]
  [ 3.   4.5  5.3]
  [ 6.   7.7  8.1]]

 [[ 9.5 10.  11.2]
  [12.7 13.1 14.5]
  [15.6 16.1 17.7]]

 [[18.7 19.1 20.6]
  [21.7 22.4 23.5]
  [24.9 25.5 26.7]]]
shape :(3, 3, 3)
